---
# エラーについて
# fatal: [server2]: FAILED! => {"msg": "Using a SSH password instead of a key is not possible because Host Key checking is enabled and sshpass does not support this.  Please ad
# d this host's fingerprint to your known_hosts file to manage this host."}
# ansible_projects/ansible.cfg host_key_checking=False追加
- hosts: webservers
  roles:
    - common
    - webserver
...